"""Initial tables

Revision ID: 307a9155ab3a
Revises: 
Create Date: 2026-03-07 15:21:01.543276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307a9155ab3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('bodyPartID', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bodyPartID'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_body_parts_bodyPartID'), 'body_parts', ['bodyPartID'], unique=False)
    op.create_table('meal_types',
    sa.Column('mealTypeID', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mealTypeID'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_meal_types_mealTypeID'), 'meal_types', ['mealTypeID'], unique=False)
    op.create_table('question_answers',
    sa.Column('qaID', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('qaID')
    )
    op.create_index(op.f('ix_question_answers_qaID'), 'question_answers', ['qaID'], unique=False)
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_userID'), 'users', ['userID'], unique=False)
    op.create_table('exercise_videos',
    sa.Column('videoID', sa.Integer(), nullable=False),
    sa.Column('bodyPartID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('videoUrl', sa.String(), nullable=False),
    sa.Column('thumbnailUrl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bodyPartID'], ['body_parts.bodyPartID'], ),
    sa.PrimaryKeyConstraint('videoID')
    )
    op.create_index(op.f('ix_exercise_videos_videoID'), 'exercise_videos', ['videoID'], unique=False)
    op.create_table('recipes',
    sa.Column('recipeID', sa.Integer(), nullable=False),
    sa.Column('mealTypeID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('prepTime', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mealTypeID'], ['meal_types.mealTypeID'], ),
    sa.PrimaryKeyConstraint('recipeID')
    )
    op.create_index(op.f('ix_recipes_recipeID'), 'recipes', ['recipeID'], unique=False)
    op.create_table('weight_records',
    sa.Column('recordID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('recordDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('recordID')
    )
    op.create_index(op.f('ix_weight_records_recordID'), 'weight_records', ['recordID'], unique=False)
    op.create_table('favorites',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('recipeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipeID'], ['recipes.recipeID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'recipeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_index(op.f('ix_weight_records_recordID'), table_name='weight_records')
    op.drop_table('weight_records')
    op.drop_index(op.f('ix_recipes_recipeID'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_exercise_videos_videoID'), table_name='exercise_videos')
    op.drop_table('exercise_videos')
    op.drop_index(op.f('ix_users_userID'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_question_answers_qaID'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_meal_types_mealTypeID'), table_name='meal_types')
    op.drop_table('meal_types')
    op.drop_index(op.f('ix_body_parts_bodyPartID'), table_name='body_parts')
    op.drop_table('body_parts')
    # ### end Alembic commands ###
